### ISSUE TITLE
Access Denied when using apoc.import 

### ISSUE THREAD

**Issue by colintkn** [neo4j/apoc#482]
I've deployed neo4j on kubernetes. 

I've created a serviceAccount with annotations to a role which permissions to run S3 commands. The necessary jar files has been downloaded as specified here https://neo4j.com/docs/apoc/5/import/web-apis/#_using_s3_protocol. 

The jar files are in the /plugins directory. 
```
neo4j@neo4j-0-0:~/plugins$ ls
README.txt            aws-java-sdk-core-1.12.136.jar  httpclient-4.5.13.jar
apoc-5.10.0-core.jar  aws-java-sdk-s3-1.12.136.jar    httpcore-4.4.15.jar
aws                   awscliv2.zip                    joda-time-2.10.13.jar
```

But an APOC call will not work in the cypher-shell of the pod.
```
CALL apoc.import.csv([{fileName: "s3://s3.ap-southeast-1.amazonaws.com/xxxx/
neo4j_import/xxxx.csv", labels: ["entities"
]}], [], {ignoreDuplicateNodes: true, ignoreBlankString: true});
```

It yields this error:
```
Failed to invoke procedure `apoc.import.csv`: Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied;
```
Is there a reason why the APOC plugin does not get credentials from the serviceAccount. When the node where the pod is running on has the S3 policies attached to it, then the apoc command works. It seems like APOC is using the permissions from the node rather than the service account.

Here are the configurations 
```
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxx:role/neo4j-eks
  creationTimestamp: "2023-08-23T02:11:45Z"
  name: neo4j
  namespace: neo4j
```

A check on the pod shows the correct role being used
```
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::xxxxxx:role/neo4j-eks
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
````
Here are the environment variables from the pod

```
neo4j@neo4j-0-0:~$ env | grep AWS
AWS_DEFAULT_REGION=ap-southeast-1
AWS_REGION=ap-southeast-1
AWS_ROLE_ARN=arn:aws:iam::xxxxxxx:role/neo4j-eks
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional

```

apoc_config:
```
apoc_config:
  apoc.import.file.enabled: "true"
  apoc.import.file.use_neo4j_config: "true"
  apoc.export.file.enabled: "true"
```

configuration:
```
config:
  server.metrics.prometheus.enabled: "true"
  server.metrics.prometheus.endpoint: "0.0.0.0:12004"
  dbms.logs.http.enabled: "true"
  server.logs.debug.enabled: "true"
  # Configure and installl APOC core https://neo4j.com/docs/operations-manual/current/kubernetes/plugins/
  server.config.strict_validation.enabled: "false"
  dbms.security.procedures.allowlist: "apoc.*"
  dbms.security.procedures.unrestricted: "apoc.*,bloom.*"
```
